# fly.toml app configuration file generated for code-racer-wss on 2023-07-25T13:35:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "code-racer-wss"
primary_region = "atl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
