version: "3.7"
services:
  _build:
    image: newsletter-image
    command: ["echo", "build completed"]
    build:
      context: .
      dockerfile: Dockerfile

  shell:
    image: newsletter-image
    container_name: shell
    depends_on:
      - _build
    command: tail -f /dev/null
    environment:
      REGION: us-east-1
      ACCESS_KEY: local
      SECRET_KEY: local
      SES_ENDPOINT: http://ses-local:9001
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      HOST_NAME: http://localhost:3000
      NEXT_PUBLIC_API_URL: http://localhost:3010
    volumes:
      - .:/home/app
      - /home/app/node_modules

  ui:
    image: newsletter-image
    depends_on:
      - _build
    container_name: ui
    ports:
      - "3000:3000"
    entrypoint: ["yarn", "workspace", "@wdc-newsletter/ui", "dev"]
    environment:
      REGION: us-east-1
      ACCESS_KEY: local
      SECRET_KEY: local
      SES_ENDPOINT: http://ses-local:9001
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      HOST_NAME: http://localhost:3000
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: $NEXT_PUBLIC_RECAPTCHA_SITE_KEY
      # for when running cypress in a container, we need to overwrite
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3010}
      NEXT_PUBLIC_DISABLE_RECAPTCHA: $NEXT_PUBLIC_DISABLE_RECAPTCHA
    volumes:
      - .:/home/app
      - /home/app/node_modules

  api:
    image: newsletter-image
    container_name: api
    ports:
      - "3010:3010"
    entrypoint: ["yarn", "workspace", "@wdc-newsletter/api", "dev"]
    depends_on:
      - _build
    environment:
      REGION: us-east-1
      ACCESS_KEY: local
      SECRET_KEY: local
      SES_ENDPOINT: http://ses-local:9001
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      HOST_NAME: http://localhost:3000
      RECAPTCHA_SECRET: $RECAPTCHA_SECRET
      DISABLE_RECAPTCHA: $DISABLE_RECAPTCHA
    volumes:
      - .:/home/app
      - /home/app/node_modules/
      - /home/app/api/node_modules/
      - /home/app/business/node_modules/

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"

  dynamo-setup:
    image: newsletter-image
    container_name: dynamo-setup
    depends_on:
      - _build
      - dynamodb-local
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      REGION: "us-east-1"
      ACCESS_KEY: local
      SECRET_KEY: local
    restart: "no"
    entrypoint:
      ["yarn", "workspace", "@wdc-newsletter/business", "dynamo:setup"]
    volumes:
      - .:/home/app
      - /home/app/node_modules

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local

  ses-local:
    image: jdelibas/aws-ses-local
    ports:
      - "9001:9001"
    volumes:
      - "./output:/aws-ses-local/output"
