name: E2E - Cypress

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Docker Compose
        env:
          NEXT_PUBLIC_API_URL: http://api:3010
          DISABLE_RECAPTCHA: true
          NEXT_PUBLIC_DISABLE_RECAPTCHA: true
        run: |
          docker-compose up -d --build

      - name: Run tests
        run: |
          docker exec shell sh -c "./wait-for.sh http://api:3010/status && ./wait-for.sh http://ui:3000 && CYPRESS_BASE_URL=http://ui:3000 yarn workspace @wdc-newsletter/e2e cypress"
