name: Scripts - Unit Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Run tests
        run: yarn workspace @wdc-newsletter/scripts test:unit
